// image-scenes.cjs — 98 per-frame scene descriptions (anchor added by gen-image-prompts).
// Dark-background scenes (hook, even facts, penutup) say "deep dark charcoal background";
// light scenes say "soft cream background".
module.exports = {
  "01": "the orange tabby cat hugging a small cat toy, eyes half-closed in bliss, pupils dilated, drooling slightly, looking happily drunk, deep dark charcoal background, no text",
  "02": "the orange tabby cat wobbling playfully with dizzy swirl stars around its head, silly drunk expression, deep dark charcoal background, no text",
  "03": "extreme close-up of the orange tabby cat's sleepy half-closed eyes hugging a toy, tiny drool drop, deep dark charcoal background, no text",
  "04": "a lush green catnip plant with heart-shaped serrated leaves and small white flowers in a terracotta pot, glowing softly, deep dark charcoal background, no cat, no text",
  "05": "a cute mouse-shaped cat toy with dried catnip leaves spilling from a seam, the orange tabby cat sniffing it curiously, deep dark charcoal background, no text",
  "06": "the orange tabby cat looking at viewer with wide surprised eyes, one eyebrow raised, comedic seriously expression, deep dark charcoal background, no text",
  "07": "a treasure chest opening with glowing cat icons, yarn balls, whiskers and paws floating out, the orange tabby cat watching excitedly, deep dark charcoal background, no text",
  "08": "the orange tabby cat sitting calmly in a cozy armchair beside a warm lamp, relaxed movie-night atmosphere, deep dark charcoal background, no text",
  "09": "the orange tabby cat standing beside a tall catnip plant, nose raised sniffing the leaves, soft cream background, no text",
  "10": "botanical illustration of a catnip plant with mint-family square stem and green serrated leaves, soft cream background, no cat, no text",
  "11": "macro view of a glowing green catnip leaf with sparkling golden particles floating above it, soft cream background, no cat, no text",
  "12": "close-up of the orange tabby cat's pink nose sniffing glowing green aroma particles drifting from a catnip leaf, soft cream background, no text",
  "13": "stylized cross-section of a cat head showing a glowing brain with signal waves traveling from the nose, scientific illustration, soft cream background, no text",
  "14": "the orange tabby cat rolling on its back on a carpet, paws in the air, pure joy, toys scattered around, soft cream background, no text",
  "15": "a round wall clock showing fifteen minutes passing, the orange tabby cat napping beside it, soft cream background, no text",
  "16": "the orange tabby cat sitting upright and composed with a poker face, a faint ghost of its wild self fading behind it, soft cream background, no text",
  "17": "an hourglass with sand flowing, the orange tabby cat waiting patiently beside a catnip toy, soft cream background, no text",
  "18": "two orange tabby cats side by side, one ecstatic rolling on catnip, the other calm and unimpressed, soft cream background, no text",
  "19": "a row of ten cat silhouettes with seven highlighted in coral showing a percentage statistic, soft cream background, no text",
  "20": "a tiny orange tabby kitten sitting calmly next to a catnip sprig, completely uninterested, yawning, soft cream background, no text",
  "21": "the orange tabby house cat in a spotlight with big wild cat shadows on the wall behind it, soft cream background, no text",
  "22": "a majestic tiger, a lion and a leopard lounging together around a large catnip plant, blissful expressions, soft cream background, no text",
  "23": "the orange tabby cat rolling happily on a carpet with a cartoon thought bubble showing swirling aroma, soft cream background, no text",
  "24": "the orange tabby cat curled up asleep on a round cushion, moon and stars above, deep dark charcoal night background, no text",
  "25": "the orange tabby cat peeking with one eye open from under a blanket, cozy dim room, deep dark charcoal background, no text",
  "26": "the orange tabby cat sleeping deeply on a windowsill with Zzz symbols floating, deep dark charcoal background, no text",
  "27": "a clock face with sixteen hours shaded, the orange tabby cat sleeping across the clock hands, deep dark charcoal background, no text",
  "28": "a tiny kitten and a senior gray-muzzled orange cat sleeping side by side, a twenty-hour clock faintly behind, deep dark charcoal background, no text",
  "29": "a human silhouette sleeping in a huge soft bed next to the orange tabby cat also asleep, dreamlike cozy scene, deep dark charcoal background, no text",
  "30": "the orange tabby cat lying lazily but with a stern not-lazy expression, arms crossed, deep dark charcoal background, no text",
  "31": "a wild ancestor cat silhouette stalking through grass at night, energy glowing in its muscles, deep dark charcoal background, no text",
  "32": "split scene, day side with the orange tabby cat asleep in a sunbeam, night side with the same cat zooming energetically, deep dark charcoal background, no text",
  "33": "a glowing alarm clock inside the orange tabby cat's silhouette at midnight, energetic pose, deep dark charcoal background, no text",
  "34": "the orange tabby cat sitting upright, chest vibrating with soft sound waves, gentle purring, soft cream background, no text",
  "35": "the orange tabby cat on a vet clinic table trembling slightly but purring, caring hands nearby, soft cream background, no text",
  "36": "the orange tabby cat with a confused questioning expression, sound waves around its head, soft cream background, no text",
  "37": "the orange tabby cat smiling with eyes closed, heart-shaped purr waves floating up, soft cream background, no text",
  "38": "a sound wave diagram with a glowing band between 25 and 150 hertz, the orange tabby cat's purr at the center, soft cream background, no text",
  "39": "a stylized glowing cat skeleton with a mending bone highlighted, healing frequency waves washing over it, soft cream background, no text",
  "40": "the orange tabby cat wrapped in a warm glowing aura like a self-healing cocoon, purring peacefully, soft cream background, no text",
  "41": "extreme close-up of the orange tabby cat's face with long elegant whiskers fanning out, deep dark charcoal background, no text",
  "42": "the orange tabby cat squeezing through a narrow gap between two boxes, whiskers touching both sides, deep dark charcoal background, no text",
  "43": "the orange tabby cat pausing at a doorway, whiskers spread forward measuring the opening, deep dark charcoal background, no text",
  "44": "a diagram illustration showing the orange tabby cat's whisker span exactly matching its body width with a glowing measurement arc, deep dark charcoal background, no text",
  "45": "the orange tabby cat approaching a gap, whiskers scanning like radar beams touching the edges, deep dark charcoal background, no text",
  "46": "a human face with giant cat whiskers attached looking puzzled at a narrow door, humorous, deep dark charcoal background, no text",
  "47": "two panels, relaxed orange tabby cat with whiskers flat on cheeks, alert cat with whiskers pushed forward, deep dark charcoal background, no text",
  "48": "the orange tabby cat with huge glowing green eyes and large upright ears, portrait, soft cream background, no text",
  "49": "a dark room with a stumbling human silhouette bumping into furniture while the orange tabby cat walks gracefully past, soft cream background, no text",
  "50": "cross-section diagram of a cat eye showing the glowing tapetum lucidum layer reflecting light back, soft cream background, no text",
  "51": "the orange tabby cat seeing clearly in a dim blue room, six-times vision shown as a bright clear inset, soft cream background, no text",
  "52": "the orange tabby cat at night with both eyes glowing bright like lanterns, a flashlight beam hitting them, soft cream background, no text",
  "53": "close-up of the orange tabby cat's ear with sound waves of different frequencies arriving, high ones glowing, soft cream background, no text",
  "54": "the orange tabby cat staring intently at an empty corner of a room, ears rotated forward, mysterious but cute, soft cream background, no text",
  "55": "the orange tabby cat's ear catching tiny sound waves from a mouse scratching inside a wall, x-ray view, soft cream background, no text",
  "56": "the orange tabby cat licking its lips looking at food, tongue out, deep dark charcoal background, no text",
  "57": "the orange tabby cat sniffing a small ice cream cone unimpressed, then turning toward a fish with excitement, deep dark charcoal background, no text",
  "58": "a row of desserts, cake, ice cream, candy, with a big crossed-out symbol, the orange tabby cat indifferent, deep dark charcoal background, no text",
  "59": "a diagram of a cat tongue with taste buds, the sweet receptor slot empty and greyed out, deep dark charcoal background, no text",
  "60": "the orange tabby cat watching a human eat cake, calmly sitting nearby, curious but not begging, deep dark charcoal background, no text",
  "61": "the orange tabby cat licking a tiny bit of cream from a spoon, enjoying the fat not the sugar, deep dark charcoal background, no text",
  "62": "the orange tabby cat with mouth open mid-meow, a speech bubble shape floating, soft cream background, no text",
  "63": "two orange tabby cats passing each other on a street in silence, only tail gestures, soft cream background, no text",
  "64": "the orange tabby cat meowing loudly up at a sleepy human, morning kitchen, soft cream background, no text",
  "65": "the orange tabby cat with a speech bubble containing a secret glowing code, talking to a human who understands, soft cream background, no text",
  "66": "the orange tabby cat meowing beside an empty food bowl at sunrise, dramatic spotlight, soft cream background, no text",
  "67": "extreme close-up of the orange tabby cat's pink nose leather with unique bumpy texture, deep dark charcoal background, no text",
  "68": "a playful police-station style scene with a fingerprint card next to a cat nose-print card, the orange tabby cat posing, deep dark charcoal background, no text",
  "69": "the orange tabby cat pressing its nose against glass leaving a nose print, unique pattern visible, deep dark charcoal background, no text",
  "70": "four different cat noses in a grid, each with a distinct texture pattern, deep dark charcoal background, no text",
  "71": "the orange tabby cat turning its head far around, owl-like, deep dark charcoal background, no text",
  "72": "the orange tabby cat looking directly backwards without moving its body, 180 degree head turn, deep dark charcoal background, no text",
  "73": "the orange tabby cat lying flat lazily but head turned around watching behind, comedic, deep dark charcoal background, no text",
  "74": "the orange tabby cat mid-leap in the air, body arched gracefully, soft cream background, no text",
  "75": "the orange tabby cat falling from a wardrobe, twisting mid-air to land on its feet, soft cream background, no text",
  "76": "a sequence diagram of the orange tabby cat rotating mid-fall, back down, twist, feet down, landing, soft cream background, no text",
  "77": "a glowing flexible cat spine bending like a spring, anatomical illustration, soft cream background, no text",
  "78": "the orange tabby cat landing softly on its feet from a high shelf, gymnast pose, soft cream background, no text",
  "79": "the orange tabby cat leaping across a huge gap between two rooftops, motion trail showing six body lengths, soft cream background, no text",
  "80": "a human attempting a super long jump over a basketball court, comparison arrow to the orange tabby cat, humorous, soft cream background, no text",
  "81": "the orange tabby cat licking its own paw and washing its face, grooming, deep dark charcoal background, no text",
  "82": "the orange tabby cat contorted licking its belly, tongue out, silly grooming pose, deep dark charcoal background, no text",
  "83": "a pie chart showing half of waking hours spent grooming, the orange tabby cat licking in the center, deep dark charcoal background, no text",
  "84": "the orange tabby cat in warm sunlight, calm and dry, a thermometer nearby, deep dark charcoal background, no text",
  "85": "close-up of the orange tabby cat's paw pad with tiny glowing sweat droplets, deep dark charcoal background, no text",
  "86": "tiny wet paw prints walking across a wooden floor, the orange tabby cat looking stressed at a window, deep dark charcoal background, no text",
  "87": "the orange tabby cat sitting beside a birthday cake with number candles, soft cream background, no text",
  "88": "a big chalkboard equation of cat years versus human years with a question mark and cross-out, the orange tabby cat shrugging, soft cream background, no text",
  "89": "a scale balancing a kitten on one side and a surprised human teenager on the other, soft cream background, no text",
  "90": "a one-year-old orange tabby kitten beside a fifteen-year-old human teenager illustration, growth chart, soft cream background, no text",
  "91": "a two-year-old orange tabby cat beside a young adult human illustration, growth chart, soft cream background, no text",
  "92": "a staircase chart rising four steps per year, the orange tabby cat climbing it gracefully, soft cream background, no text",
  "93": "a dignified senior orange tabby cat with a tiny bit of grey fur, leaping playfully despite an age badge, soft cream background, no text",
  "94": "a collage of eleven small glowing scenes around the orange tabby cat, catnip, sleeping, purring, whiskers, glowing eyes, cake, meowing, nose, jumping, grooming, birthday, deep dark charcoal background, no text",
  "95": "the orange tabby cat chasing its own tail in a sunbeam, warm living room, deep dark charcoal background, no text",
  "96": "the orange tabby cat pawing at a mysterious paper bag, curious wide eyes, deep dark charcoal background, no text",
  "97": "the orange tabby cat waving a paw at the viewer, warm friendly farewell, deep dark charcoal background, no text",
  "98": "the orange tabby cat walking away into a warm sunset, tail high, looking back once, farewell scene, deep dark charcoal background, no text",
};
